server:  port: 2100

spring:  application:    name: crypto-dash
  datasource:    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Dog@08  jpa:    database: POSTGRESQL    hibernate:      ddl-auto: none    properties:      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect    show-sql: false  sql:    init:      continue-on-error: true    allowed.cors.origins: "*"allowed.cors.headers: "*"    